//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dv402.S1.L01A.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1dv402.S1.L01A.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck ny tangent för ny beräkning - Esc avslutar.
        /// </summary>
        internal static string Continue_Prompt {
            get {
                return ResourceManager.GetString("Continue_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lappar.
        /// </summary>
        internal static string Denomination_Form1 {
            get {
                return ResourceManager.GetString("Denomination_Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kronor.
        /// </summary>
        internal static string Denomination_Form2 {
            get {
                return ResourceManager.GetString("Denomination_Form2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange ett heltal större än eller lika med totalsumman..
        /// </summary>
        internal static string LowCash_Error {
            get {
                return ResourceManager.GetString("LowCash_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange erhållet belopp: .
        /// </summary>
        internal static string PayedSum_Prompt {
            get {
                return ResourceManager.GetString("PayedSum_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------.
        /// </summary>
        internal static string RecieptLine {
            get {
                return ResourceManager.GetString("RecieptLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontant.
        /// </summary>
        internal static string RecieptPayedSum {
            get {
                return ResourceManager.GetString("RecieptPayedSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka .
        /// </summary>
        internal static string RecieptReturnSum {
            get {
                return ResourceManager.GetString("RecieptReturnSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öresavrundning.
        /// </summary>
        internal static string RecieptRounding {
            get {
                return ResourceManager.GetString("RecieptRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVITTO.
        /// </summary>
        internal static string RecieptStart {
            get {
                return ResourceManager.GetString("RecieptStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalt.
        /// </summary>
        internal static string RecieptSubtotal {
            get {
                return ResourceManager.GetString("RecieptSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Att betala.
        /// </summary>
        internal static string RecieptTotal {
            get {
                return ResourceManager.GetString("RecieptTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange totalsumma: .
        /// </summary>
        internal static string Total_Prompt {
            get {
                return ResourceManager.GetString("Total_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! &apos;{0}&apos; kan inte tolkas som en giltig summa pengar..
        /// </summary>
        internal static string WrongInput_Error {
            get {
                return ResourceManager.GetString("WrongInput_Error", resourceCulture);
            }
        }
    }
}
